### ISSUE TITLE
 Build client side

### ISSUE THREAD

**Issue by jp-knj** [jp-knj/timer#1]
#### Description
- Setup Webpack for React with TypeScript

#### Files
A list of relevant files for this issue. This will help people navigate the project and offer some clues of where to start.

#### To produce
If this issue is describing a bug, include some steps to reproduce the behavior.

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [x] Install some files
- [x] configure webpack & typescript
- [x] setup react, react-dom
